
```{r}
#import library
library(readxl)
library(dplyr)
library(ggplot2)
library(janitor)
```



```{r}
#Import dataset
df_normalize_cluster <- read_excel("final_mode_3_cluster.xlsx")

df_normalize_cluster <- df_normalize_cluster %>%
                        mutate(Cluster = Cluster + 1)

merged_df <- read_excel("merged_df.xlsx")

merged_df <- merged_df %>%
             mutate(Cluster = Cluster + 1)


```

```{r warning=FALSE, include=FALSE}
#number of words per season
df_company_per_clusters <- df_normalize_cluster%>%  
                     dplyr::group_by(Cluster) %>%
                     dplyr::summarise(number_company=n()) 

total_company=sum(df_company_per_clusters$number_company)

df_company_per_clusters$percentage=paste(round((df_company_per_clusters$number_company/total_company)*100,0),"%")

df_company_per_clusters$round_company <- paste(round(df_company_per_clusters$number_company/ 1000, 1), "K")
```


```{r}
#graph per cluster
graph_nb_company_per_cluster <-ggplot2::ggplot(data = df_company_per_clusters,
                                            aes(x = Cluster,
                                                y = number_company))+
                              ggplot2::ylim( 0,50000)+
                             ggplot2::geom_col(colour = "#7B3A96",
                                              fill="#3f2d54",
                                              linewidth=1.3) +
                            ggplot2::geom_text(aes(label = percentage),
                                               color="White",
                                               hjust=0.5,
                                               vjust=1.2,
                                               size = 6)+
                            ggplot2::geom_text(aes(label = round_company),
                                               color="Black",
                                               hjust=0.5,
                                               vjust=-0.5,
                                               size = 6)+
                            ggplot2::labs(title = "What is the number of companies per cluster?", 
                                          subtitle = "Proportion and number of companies per cluster",
                                          x = "Clusters",
                                          y = "Number of companies")+
                            ggplot2::theme(plot.title = element_text(hjust = 0.5,
                                                                     vjust=3,
                                                                     size =12),
                                           plot.subtitle = element_text(hjust = 0.5,
                                                                        vjust=0,size =9,
                                                                        face="italic"),
                                           legend.position="right",
                                           legend.title= element_text(face="bold"), 
                                           axis.title.x=element_text(face="bold",
                                                                     margin = margin(t = 10)),
                                           panel.background = element_blank(),
                                           axis.title.y=element_text(face="bold",
                                                                     margin = margin(r = 10)),
                                           plot.caption = element_text(face = "italic"),
                                           axis.line=element_line())

graph_nb_company_per_cluster
```
```{r warning=FALSE, include=FALSE}
df_legal_form_per_cluster <- janitor::tabyl(df_normalize_cluster,
                                            LegalForm, 
                                          Cluster)%>%
                           janitor::adorn_totals("row")%>%
                           janitor::adorn_percentages() %>% 
                           tidyr::pivot_longer(cols=-LegalForm,
                                               values_to = "Cluster") %>%
                           filter(LegalForm!='Total') 

names(df_legal_form_per_cluster)[2] <- "Clusters"
names(df_legal_form_per_cluster)[3] <- "Percentage"

df_legal_form_per_cluster$LegalForm <- gsub("Autre entité de droit luxembourgeois", "Droit Luxembourgeois(2)", df_legal_form_per_cluster$LegalForm)

df_legal_form_per_cluster$LegalForm <- gsub("Entité de droit étranger", "Droit étranger(2)", df_legal_form_per_cluster$LegalForm)


```


```{r}
graph_legal_form_per_cluster <- ggplot2::ggplot(df_legal_form_per_cluster,
                                      aes(x = LegalForm, 
                                          y = Percentage, 
                                          fill = Clusters,
                                          label = scales::percent(Percentage))) +
                                ggplot2::geom_col(position = 'fill',
                                               color="grey",
                                               width = 0.8)+
                             ggplot2::scale_fill_manual(values = c("#837fb9", "#63459a", "#3f2d54"),
                                                        name="Clusters")+
                             ggplot2::scale_y_continuous(labels = scales::percent)+
                             ggplot2::geom_text(aes(label = paste0(round(Percentage,2)*100,"%")),
                                                position = position_stack(vjust = 0.5), 
                                                size = 4,
                                                color="white")+
                             ggplot2::labs(title="How the different companies legal form are distributed per clusters?",
                                      subtitle="Percentage of Legal form companies per cluster ",
                                      y="Percentage in each clusters", 
                                      x="Companies LegalForm",
                                       caption="(1)=Autre entité de droit luxembourgeois \n (2)=Entité de droit étranger") + 
                             ggplot2::theme(plot.title = element_text(hjust = 0.5,
                                                              vjust=3,
                                                              size =12),
                                      plot.subtitle = element_text(hjust = 0.5,
                                                                   vjust=0,
                                                                   size =9,
                                                                   face="italic"),
                                      legend.position="bottom",
                                      legend.title= element_text(face="bold"), 
                                      axis.title.x=element_text(face="bold",
                                                                margin = margin(t = 10)),
                                      panel.background = element_blank(),
                                      axis.title.y=element_text(face="bold",
                                                                margin = margin(r = 10)),
                                      plot.caption = element_text(face = "italic"),
                                      axis.line=element_line())

graph_legal_form_per_cluster
```





```{r}

df_company_per_activity <- df_normalize_cluster%>%  
                     dplyr::group_by(NACEActivity) %>%
                     dplyr::summarise(number_company=n()) %>% 
                      top_n(10, number_company)

top_10 <- as.list(df_company_per_activity$NACEActivity)


df_activity_per_cluster <- janitor::tabyl(df_normalize_cluster,
                                            NACEActivity, 
                                          Cluster)%>%
                           janitor::adorn_totals("row")%>%
                           janitor::adorn_percentages() %>% 
                           tidyr::pivot_longer(cols=-NACEActivity,
                                               values_to = "Cluster")  
                           
df_activity_per_cluster_top10 <- df_activity_per_cluster[df_activity_per_cluster$NACEActivity %in%top_10, ]

names(df_activity_per_cluster_top10)[2] <- "Clusters"
names(df_activity_per_cluster_top10)[3] <- "Percentage"

```


```{r}
graph_activity_cluster <- ggplot2::ggplot(df_activity_per_cluster_top10,
                                      aes(x = NACEActivity, 
                                          y = Percentage, 
                                          fill = Clusters,
                                          label = scales::percent(Percentage))) +
                                ggplot2::geom_col(position = 'fill',
                                               color="grey",
                                               width = 0.8)+
                             ggplot2::scale_fill_manual(values = c("#837fb9", "#63459a", "#3f2d54"),
                                                        name="Clusters")+
                             ggplot2::scale_y_continuous(labels = scales::percent)+
                             ggplot2::geom_text(aes(label = paste0(round(Percentage,2)*100,"%")),
                                                position = position_stack(vjust = 0.5), 
                                                size = 3,
                                                color="white")+
                             ggplot2::labs(title="How the different companies activities are distributed per clusters?",
                                      subtitle="Percentage of companies activities per cluster (top 10)",
                                      y="Percentage in each clusters", 
                                      x="Companies Activities") + 
                             ggplot2::theme(plot.title = element_text(hjust = 0.5,
                                                              vjust=3,
                                                              size =12),
                                      plot.subtitle = element_text(hjust = 0.5,
                                                                   vjust=0,
                                                                   size =9,
                                                                   face="italic"),
                                      axis.text.x = element_text(size = 7,angle = 45, hjust = 1),
                                      legend.position="bottom",
                                      legend.title= element_text(face="bold"), 
                                      axis.title.x=element_text(face="bold",
                                                                margin = margin(t = 10)),
                                      panel.background = element_blank(),
                                      axis.title.y=element_text(face="bold",
                                                                margin = margin(r = 10)),
                                      plot.caption = element_text(face = "italic"),
                                      axis.line=element_line())

graph_activity_cluster
```

